name: larpardy

services:
  server:
    profiles:
      - prod
    build:
      context: .
      target: server
    ports:
      - "3001:3001"
    restart: unless-stopped

  client-host:
    profiles:
      - prod
    depends_on:
      - server
    build:
      context: .
      target: client
    ports:
      - "8080:80"
    restart: unless-stopped
